apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  db-init.sql: |
    CREATE DATABASE IF NOT EXISTS testdb;
    USE testdb;
    CREATE TABLE IF NOT EXISTS test_table (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL
    );
    INSERT INTO test_table (name) VALUES ('Alice'), ('Bob');
